# path to sdk scenarios csv
scenarios: config/SDK_Data.csv

# solver (cbc|cplex|gurobi)
solver: cplex

# minfin data to extract
# NOTE: these names must match names in 'format_data.py' module!
minfin_files:
  - PWR_CapitalInvestment
  - MIN_AnnualVariableOperatingCost
  - PWR_AnnualVariableOperatingCost
  - PWR_AnnualFixedOperatingCost
  - PWR_ProductionByTechnologyAnnual