# path to sdk scenarios csv
scenarios: resources/SDK_Data.csv

# minfin data to extract
# NOTE: these names must match names in 'format_data.py' module!
minfin_files:
  - PWR_CapitalInvestment
  - MIN_AnnualVariableOperatingCost
  - PWR_AnnualVariableOperatingCost
  - PWR_AnnualFixedOperatingCost
  - PWR_ProductionByTechnologyAnnual
    
# solver (cbc|cplex|gurobi)
solver: cplex