# path to sdk scenarios csv
scenarios: resources/SDK_Data.csv

# minfin data to extract
minfin_files:
  # - CapitalInvestment
  - AnnualVariableOperatingCost
  - AnnualFixedOperatingCost
    
# solver (cbc|cplex|gurobi)
solver: cplex